
[package]
name    = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec.workspace     = true
k256.workspace       = true
num-bigint.workspace = true

elliptic-curve.workspace = true

